### ISSUE TITLE
Theme map

### ISSUE THREAD

**Issue by matrix59920** [Fernando-Marquardt/avalon#1]
hello So here I already want to thank you for your work but I am having a problem that I see the map, and not in the bootstrap design how to change it I would like the site and the same design can you help me?

![aaaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/13590587/9018561/4fc1836c-37e0-11e5-87d0-1cc581392995.JPG)

**Comment by matrix59920** [comment]
Help me please

**Comment by fernando-marquardt** [comment]
I will take a look on it.

**Comment by matrix59920** [comment]
ok thanks you

**Comment by fernando-marquardt** [comment]
Take a look at the modified town page and let me know if you find any issue, please.

**Comment by matrix59920** [comment]
thank you again for correction but toujour to map the bug as you can see

![bug avalon 2](https://cloud.githubusercontent.com/assets/13590587/9154049/0c426502-3e7f-11e5-9bde-5fe572760051.JPG)

**Comment by fernando-marquardt** [comment]
Which browser are you using? I can't quite reproduce your problem.

**Comment by matrix59920** [comment]
Hello

## Hello I use chrome firefox and IE and I have the same problem

Envoyé de l'application Mail.Ru pour Android mardi, 11 août 2015, 06:11PM +02:00 de Fernando Marquardt < notifications@github.com> :

**Comment by fernando-marquardt** [comment]
Have you changed something in the code? Does this happened after something you did in the game, like queuing a building or troops?

**Comment by matrix59920** [comment]
I do not touch anything I just made a new installation and the map like that even without launching construction

**Comment by matrix59920** [comment]
Help me please

**Comment by fernando-marquardt** [comment]
Sorry, I can't reproduce your problem. Are you running it local?

Did you try to clear your cache?
